name: dynmap
version: "${project.version}-${BUILD_NUMBER}"
description: Dynamic map for Spout - provides Google Maps style web site for Spout server
authors: [ mikeprimm, FrozenCow ]

main: org.dynmap.spout.DynmapPlugin
load: startup

platform: BOTH
